version: '3'
services:
    sounder-web:
        container_name: sounder-web
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /app
        command: sh -c "yarn install && yarn dev --host"
        ports:
            - 3001:5173
        volumes:
            - .:/app
        networks:
            - sounder
networks:
    sounder
